name: Build Kivy APK

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - name: Repo indir
        uses: actions/checkout@v4

      - name: Java 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: Android SDK
        uses: android-actions/setup-android@v3

      - name: Android SDK paketleri (SADECE 33.0.2)
        run: |
          yes | sdkmanager --licenses
          sdkmanager \
            "platform-tools" \
            "platforms;android-33" \
            "build-tools;33.0.2"

      - name: Sistem paketleri
        run: |
          sudo apt update
          sudo apt install -y \
            python3 python3-pip git zip unzip \
            build-essential ccache \
            libncurses5 libstdc++6 \
            libffi-dev libssl-dev

      - name: Buildozer
        run: |
          pip3 install --user buildozer
          pip3 install --user cython==0.29.36

      - name: Buildozer cache + kendi SDK temizle
        run: |
          rm -rf ~/.buildozer

      - name: APK oluştur
        run: |
          export ANDROID_HOME=/usr/local/lib/android/sdk
          export ANDROID_SDK_ROOT=/usr/local/lib/android/sdk
          export PATH=$PATH:$HOME/.local/bin
          buildozer android debug

      - name: APK yükle
        uses: actions/upload-artifact@v4
        with:
          name: kivy-apk
          path: bin/*.apk
